### ISSUE TITLE
Support for Views without Headers

### ISSUE THREAD

**Issue by jacobtabak** [timehop/sticky-headers-recyclerview#10]
Since there are no HeaderViews or FooterViews in RecyclerView, we should support views not having headers, so they can be used as header and footer views.

I think a decent approach will be to return a header id < 0 to indicate the view shouldn't have a header.

**Comment by nibarius** [comment]
Hiding all headers with an id < 0 makes this harder to use for me. My headers are (more or less) arbitrary strings so I can't just go by the initial letter the header id must be based on the whole string for me.

header.hashCode() is a very convenient way of generating an id based on the whole string. However this returns negative values for many strings meaning I don't get any headers.

**Comment by jacobtabak** [comment]
Feel free to submit a PR that overrides the default behavior.  Or use
Math.abs() :)

**Comment by nibarius** [comment]
I ended up using Math.abs(), it doesn't feel right to mess with the return value of hashCode(), but I think it should be safe to do in my case.
