### ISSUE TITLE
How to get to a certain item, stickty headers disappear?

### ISSUE THREAD

**Issue by aaatttcccc** [timehop/sticky-headers-recyclerview#110]
How to get to a certain item, stickty headers disappear?

**Comment by jacobtabak** [comment]
Not enough detail, please feel free to reopen if you can explain your issue.

**Comment by aaatttcccc** [comment]
Like Google calendar.
Sliding to The list of the item, not the head
Can item, Can head

[https://play.google.com/store/apps/details?id=com.google.android.calendar&hl=zh_CN](url)

I'm sorry, my English is not very good.
