### ISSUE TITLE
Adding Items To Top of Data Causes Layout Issues

### ISSUE THREAD

**Issue by jsonfry** [timehop/sticky-headers-recyclerview#26]
Using `adapter.notifyItemRangeInsert(0, newItemsSize)` causes headers initially to be drawn in the wrong place, and gaps to be added between items where there shouldn't be.

We are calling `headersDecor.invalidateHeaders()`.

**Comment by jsonfry** [comment]
But calling `recyclerView.setItemAnimator(null)` seems to fix that, so maybe this issue is a duplicate of https://github.com/timehop/sticky-headers-recyclerview/issues/5

**Comment by jacobtabak** [comment]
Yeah there are some fundamental issues with animators that can't be fixed as long as this is implemented as a decorator.
