### ISSUE TITLE
Headers not updating when calling notifyDataSetChanged on adapter

### ISSUE THREAD

**Issue by meilers** [timehop/sticky-headers-recyclerview#30]
I use a cursorloader that updates the adapter data set by calling notifyDataSetChanged. All the cells that aren't sticky get updated, but not the sticky headers. In fact, onBindHeaderViewHolder doesn't get called at all.

**Comment by jacobtabak** [comment]
Thanks for the report, should be a quick fix. We'll look into it right away.

**Comment by romanrodriguez-sp** [comment]
My headers appear but without text, background only. Can be the same issue?

**Comment by jacobtabak** [comment]
Doesn't sound related, please feel free to open another issue with code
sample and we can look into it. Specifically the header view holder
creation and binding.

**Comment by romanrodriguez-sp** [comment]
Yes, you are right. The problem was the text view style.

I added a new issue:
android:singleLine=true on xml makes header text do not appear #33

**Comment by meilers** [comment]
Any follow up on this?

**Comment by jacobtabak** [comment]
Sorry for the delay.  You can call `decoration.invalidateHeaders()` and `recyclerView.invalidate()` for now.  I'll try to add proper support for invalidating the dataset today.

**Comment by jacobtabak** [comment]
@meilers The decoration isn't directly aware of the RecyclerView's adapter so there's no way to do this automatically.  I recommend you add this code when creating your RecyclerView.Adapter:

```
    adapter.registerAdapterDataObserver(new RecyclerView.AdapterDataObserver() {
      @Override public void onChanged() {
        super.onChanged();
        decoration.invalidateHeaders();
      }
    });
```

**Comment by meilers** [comment]
Awesome Jacob. Thanks!

**Comment by Gruneau** [comment]
@jacobtabak I've encountered a similar problem when using the sticky headers. I update the list by swapping out the cursor and calling notifydatasetchanged(). When one extra item is added to the top of the list the entire list expands downwards but the headers remain static (thus in the wrong position by one step). Any ideas? 

I've tried invalidating the headers but it does not seem to solve the issue.

**Comment by jacobtabak** [comment]
Nothing sticks out - but if you can post a sample app to github that reproduce the issue I can take a look.

**Comment by Gruneau** [comment]
@jacobtabak I found the fix, apparently I had to: 
1) remove the current decoration on the list
2) create a new instance of the adapter
3) assign the new adapter to the recyclerview
4) add a new instance of the header decoration to the recyclerview

like this:

        mRecyclerView.removeItemDecoration(mDecoration);
        mAdapter = getAdapter();
        mAdapter.swapCursor(data);
        mRecyclerView.setAdapter(mAdapter);
        mDecoration = new StickyRecyclerHeadersDecoration(mAdapter);
        mRecyclerView.addItemDecoration(mDecoration);

**Comment by jacobtabak** [comment]
This really shouldn't be necessary.

**Comment by venkataramanaj** [comment]
in sticky header i have check box, when check box checked notify the recyclerview, but not getting refreshed, after scroll, then it is getting refershed

**Comment by jacobtabak** [comment]
Since the headers are just decorations they are not interactive. So check
boxes won't work. Sorry!
