### ISSUE TITLE
First header position

### ISSUE THREAD

**Issue by grunk** [timehop/sticky-headers-recyclerview#31]
Hello,
I'm testing your library with the sample application.

I noticed that if i remove the first element of the dataset (Animals Below!) the first header is drawn after the first element of the list.
In this case I have :  Abyssinian [A header] Adelie Penguin ... whereas the header was expected first.

Does that mean we always need to add a dummy elementto get the header well positioned ?

Thanks

**Comment by mjtrefethen** [comment]
Try removing the condition to return -1.

https://github.com/timehop/sticky-headers-recyclerview/blob/master/sample/src/main/java/com/timehop/stickyheadersrecyclerview/sample/MainActivity.java#L97

```
@Override
    public long getHeaderId(int position) {
      if (position == 0) {
        return -1;
      } else {
        return getItem(position).charAt(0);
      }
    }
```
