### ISSUE TITLE
Margin on CardView applies to headers in odd ways.

### ISSUE THREAD

**Issue by mjtrefethen** [timehop/sticky-headers-recyclerview#34]
For example, if a top margin is set on the CardView the sticky headers are all pushed down by that amount, see attached screenshot. This CardView has a 4dp top margin with the intent of keeping the initial content from touching the toolbar but it moves the header down which causes odd scrolling effects. I have added background color to the headers for visibility.

In addition if a start margin is set it will only affect the "stuck" header. If I set a start margin the top header will have that margin while the second will not, until it becomes the stuck header. At that point it will jump right to the margin position.

Should the drawing of the headers even obey the margins of the cards or should it only be controlled by its own layout properties and that of the recyclerview?

![screenshot_2015-03-20-02-10-54](https://cloud.githubusercontent.com/assets/8259966/6746895/2c1ed0a6-cea7-11e4-91e5-4ca511b8705d.png)

**Comment by jacobtabak** [comment]
Are you using master or the version from maven central? There was a recent
PR that added better support for child views with margins. If you're still
having issues please either link to a repo that reproduces the problem or
dig into the code and submit a pull request.

**Comment by jacobtabak** [comment]
Please feel free to reopen if and when you add more details or instructions to reproduce.
