### ISSUE TITLE
Headers with different heights do not scroll properly

### ISSUE THREAD

**Issue by imbeyondboredom** [timehop/sticky-headers-recyclerview#36]
If you change onBindViewHeader in MainActivity.java in the samples in the following way you will see that the headers overlap in an odd way when scrolling if they are different sizes. Scroll down to when E and F occur in the sample.

@Override
    public void onBindHeaderViewHolder(RecyclerView.ViewHolder holder, int position) {
      TextView textView = (TextView) holder.itemView;
        if(position % 2 ==0 ) {
            textView.setText("test\n"+String.valueOf(getItem(position).charAt(0)));
        } else {
            textView.setText(String.valueOf(getItem(position).charAt(0)));
        }
      holder.itemView.setBackgroundColor(getRandomColor());
    }

![device-2015-03-25-083130](https://cloud.githubusercontent.com/assets/86616/6824546/984b4766-d2c9-11e4-8750-19d2395cd53c.png)

**Comment by jacobtabak** [comment]
Thanks for the report.  I've reproduced the issue but don't have a fix just yet.

**Comment by jacobtabak** [comment]
Can you please try out the fix in PR #37?

**Comment by imbeyondboredom** [comment]
Looks good! Quick turn-around as well!
