### ISSUE TITLE
Extra spacing added every time the adapter is updated

### ISSUE THREAD

**Issue by ericlw** [timehop/sticky-headers-recyclerview#52]
Every time the adapter is refreshed in this code, the padding between headers and sections is increased. This is not the intended result

Here is the code I use to update the dataset. (ultimately notify data set is changed is called, the headerDecors are updated and the listview is reattached to the headers and the new adapter)
  
                                             if(mPerf == null)
                                                    mPerf = new PerformanceAdapter(list, context);
                                                else{
                                                    mPerf.updateList(list);
                                                }
                                                recList.removeItemDecoration(headersDecor);

                                                if(headersDecor!=null){
                                                    headersDecor.invalidateHeaders();
                                                }
                                                headersDecor = new StickyRecyclerHeadersDecoration(mPerf);
                                                recList.addItemDecoration(headersDecor);
                                                recList.setAdapter(mPerf);

**Comment by jacobtabak** [comment]
There are a few confusing things going on here - 
1. why are you removing and re-adding the decoration?
2. you're removing the decorations from the list just before checking if the decorations are null
3. you're invalidating the headers right before overwriting the variable with a new instance of the decorations

**Comment by ericlw** [comment]
1. It isn't clear that decorations updated with the adapter or listview

2. and 3. some of this is the remnants of trial and error

**Comment by jacobtabak** [comment]
Calling `invalidateHeaders()` will rebind the data with the adapter

**Comment by ericlw** [comment]
This seems to have solved it, setting adapter only once

      if(recList.getAdapter()==null) {
                                        headersDecor = new StickyRecyclerHeadersDecoration(mPerf);
                                        recList.addItemDecoration(headersDecor);
                                        recList.setAdapter(mPerf);
                                    }

**Comment by jacobtabak** [comment]
Nice! Thanks for using the lib!

**Comment by groomefyvik** [comment]
i am also facing the same issue and i am adding the  headerdecor only once
