### ISSUE TITLE
Header disappering

### ISSUE THREAD

**Issue by johngray1965** [timehop/sticky-headers-recyclerview#56]
I'm using your lib for a project that's displaying groups of pictures by month.  If I scroll to near the bottom, and then move up through the pictures, the sticky header disappears seemingly randomly.   When moving in the other direction its fine. 

Here's screen shot.
![device-2015-07-04-182104](https://cloud.githubusercontent.com/assets/1176259/8509608/5e6c23fc-227a-11e5-96d4-353204275805.png)

**Comment by jacobtabak** [comment]
Hey, sorry I missed this! Have you resolved your issue?  I'm happy to take a look if you create a fork that reproduces the issue.

**Comment by jacobtabak** [comment]
Feel free to reopen if you can find time to help reproduce.  Otherwise I will assume this is an issue with your implementation.

**Comment by johngray1965** [comment]
I still see this problem.  Today I submitted another bug (and a solution for it).  It now occurs to me that they are related.   I'm setting up the layout manager to preload content.  I suspect that what's causing the issue.  There are rows that recyclerview has allocated and bound that aren't visible yet.  I suspect that's causing issues.
