### ISSUE TITLE
Dancing header with 0.4.1

### ISSUE THREAD

**Issue by fjr619** [timehop/sticky-headers-recyclerview#57]
![dancing header](https://cloud.githubusercontent.com/assets/9444636/8516408/10179654-23de-11e5-9c8d-e9709309c494.gif)

i still got dancing header on new lib : 0.4.1 when i want to delete item with multiple selection. if i just delete it one by one without multiple selection, it was no problem

**Comment by jacobtabak** [comment]
Does it happen with item animations disabled?

**Comment by fjr619** [comment]
when set recyclerView.setItemAnimator(null); i didnt get dancing header on multiple delete selection

**Comment by jacobtabak** [comment]
We don't currently support animations, but if you create a fork that
reproduces the issue I'll be happy to take a look.
