### ISSUE TITLE
Empty Headers are displaying when stackfromBottom is true

### ISSUE THREAD

**Issue by shashidhar502** [timehop/sticky-headers-recyclerview#58]

**Comment by jacobtabak** [comment]
Do you mean a reversed LinearLayoutManager, where the first item is at the bottom?

**Comment by shashidhar502** [comment]
Setstackfromend true to recylerview

**Comment by jacobtabak** [comment]
Ah, it's in `LinearLayoutManager`. I'll check it out

**Comment by jacobtabak** [comment]
If the RecyclerView was stacking from bottom, you would expect to see the first header at the very bottom, right?

**Comment by shashidhar502** [comment]
I am using stacking from bottom for whats app kind of view for chats

So Sticky header should be at the top
I am seeing empty spaces when i am using this library

very thankful to library very easy to use in all the cases except this
stackfrombottom

Thank you so much once again for you library and for your quick response.


Thanks
Shashidhar

**Comment by jacobtabak** [comment]
@shashidhar502 In the sample repo I added `layoutManager.setStackFromEnd(true);` on line 60 of `MainActivity.java` and it works as expected. If you want to create a fork that reproduces your issue I will take a look at it.

**Comment by shashidhar502** [comment]
thanks jacob
 i will look in to that code.
