### ISSUE TITLE
Negative header id doesn't work

### ISSUE THREAD

**Issue by jayrambhia** [timehop/sticky-headers-recyclerview#59]
As shown in the docs, I was trying it out and some of my strings return negative hashcode and that's what I was returning in `getHeaderId()`. Whichever item returns a negative header id, header isn't created for that. I tried returning absolute value and it worked for all the headers. Is this Recyclerview issue or this library's issue?

**Comment by jacobtabak** [comment]
Check out [the documentation](https://github.com/timehop/sticky-headers-recyclerview/blob/master/library/src/main/java/com/timehop/stickyheadersrecyclerview/StickyRecyclerHeadersAdapter.java#L7-L14) for `getHeaderId` in `StickyRecyclerHeaderAdapter`, it is definitely intentional.
