### ISSUE TITLE
how to add footer in each section ? 

### ISSUE THREAD

**Issue by erumhannan** [timehop/sticky-headers-recyclerview#68]
is there any way to add footer for each section in this library ? http://www.dailymotion.com/dm_5233001e62925  same as this i need sections and stckyheaders ..... and also footer for each section ?

**Comment by jacobtabak** [comment]
Sticky footers? No. Regular footers, yes... just put your footer item as the last item with that header ID.

**Comment by erumhannan** [comment]
@jacobtabak  sorry i want sticky headers not sticky footers .....but a footer for each section ? how will i  add footer for every sections  ?

**Comment by jacobtabak** [comment]
Custom logic in your adapter. Just make the footer item the last item index that has the given header ID.

**Comment by erumhannan** [comment]
@jacobtabak may i need to apply custon logic in library adapters or in my sample folder adapters ?
