### ISSUE TITLE
Does hasStableIds=true in RecyclerArrayAdapter require a better getItemId() implementation?

### ISSUE THREAD

**Issue by webmaster128** [timehop/sticky-headers-recyclerview#80]
[RecyclerArrayAdapter.java](https://github.com/timehop/sticky-headers-recyclerview/blob/516e3798920e61baf93752266ed4c583b6f65428/sample/src/main/java/com/timehop/stickyheadersrecyclerview/sample/RecyclerArrayAdapter.java) you set `setHasStableIds(true)` but then declare

```
public long getItemId(int position) {
    return position;
  }
```

Isn't that a contradiction?

The method `getItemId()` is documented as follows

> Return the stable ID for the item at *position*. If #hasStableIds() would return false this method should return #NO_ID. The default implementation of this method returns #NO_ID
> `@param` position Adapter position to query
> `@return` the stable ID of the item at position

and in `hasStableIds()` we have

> Returns true if this adapter publishes a unique <code>long</code> value that can act as a key for the item at a given position in the data set. **If that item is relocated in the data set, the ID returned for that item should be the same.**
> `@return` true if this adapter's items have stable IDs

I think that as long we don't know a any structure of the elements, it is better to fall back to the default implementation returning `NO_ID`.

**Comment by jacobtabak** [comment]
Good point. This really only affects the sample but it should be fixed. I'll have to do some research to see why we're setting `hasStableIds` to `true`.

**Comment by webmaster128** [comment]
This is also picked up by a currently open PR: https://github.com/timehop/sticky-headers-recyclerview/pull/75/files See change in `RecyclerArrayAdapter.java`

**Comment by jacobtabak** [comment]
That should fix it, yes?

**Comment by webmaster128** [comment]
Well at least it confirms that others had problems here too.

I am not familiar with the concept of stable ids but I doubt that there is an implementation that works for all `M`.

Looking at the PR's implementation: when `M` e.g. is String and you add two different String elements that have the same content, they'll end up having the same stable id, which feels wrong to me. That cannot fulfil the requirement:

>  [...] adapter publishes a **unique** long value that can act as a key [...]

**Comment by jacobtabak** [comment]
In the sample implementation there are no duplicates, though, so the hash code of each string would be unique for this implementation. I do agree with you that this is not a valid approach for a real implementation, but this is just a sample.

**Comment by webmaster128** [comment]
Then you have the problem that the RecyclerArrayAdapter class handles different levels of abstraction. On one hand you let it hold an arbitrary list of types `M` and on the other hand you add assumptions to how it is used. Even if this class would not be used anywhere else in the world, this is a maintenance problem.

I'd suggest to define the level of abstraction you want, leaving 3 possibilities:

1. Let `M` be arbitrary, remove the implementation of `getItemId` and don't set `hasStableIds = false`
2. Let `M` be arbitrary and specify that no duplicates are allowed in `private ArrayList<M> items`,  set `hasStableIds = true`, take the PR's implementation
3. Let `M = Long`, specify that no duplicates are allowed in `private ArrayList<Long> items`,  set `hasStableIds = true`, use `getItemId() { getItem() }` as implementation

To ensure that a list does not contain any element twice is a lot of work when you don't know the data. Maybe you need something like [ListOrderedSet](https://commons.apache.org/proper/commons-collections/javadocs/api-3.2.1/org/apache/commons/collections/set/ListOrderedSet.html) or build gate keepers into every function in RecyclerArrayAdapter that adds elements.

Given that, I'd suggest to go for 1 and if you need to show how stable ids work for some specific data, derive from RecyclerArrayAdapter, set `hasStableIds = true` and add a implementation of `getItemId()` for that specific data.

ps.: The reason I am concerned about this is that examples easily make it to production code. If fact it did in this case.

**Comment by jacobtabak** [comment]
I can see why you feel strongly about it - I think the most reasonable thing to do is to make it less generic `RecyclerArrayAdapter` => `AnimalAdapter` and remove the generics and indicate that it is just for use in the sample.

**Comment by webmaster128** [comment]
Sounds like a good solution because the name suggests what the Adapter should be used for and at 
which point of the abstraction hierarchy it is placed. For the reader it indicates directly that this is something to adapt, not something to copy and derive from.

Just add a comment somewhere that an animal must only be in the list once.
