### ISSUE TITLE
RecyclerView jumps when adding items on the top

### ISSUE THREAD

**Issue by ealymbaev** [timehop/sticky-headers-recyclerview#93]
I have an autoloading (from top) list of items. When user scroll to top of the list - new items are added to the top.

I need to preserve the scroll position. The desired behaviour is to keep all the items as they are and add more items to top.

NOW when adding items to top - the list jumps a little up - thus placing the first item to the very top (not under header as it was).

Could you please fix this asap.

P.S. Thank you for the great library, works great.

**Comment by jacobtabak** [comment]
I can take a look if you fork the repo and modify the sample to reproduce
the issue that you're describing.

**Comment by ealymbaev** [comment]
I have reproduced the issue in your sample project:

https://github.com/ealymbaev/sticky-headers-recyclerview/commit/b10c2134f63c18bcde075581663802af200ee755

The list now initially loads at the bottom. You need to scroll to the very top and wait for 3 seconds (I have used postDelayed). After that you will see that the list jumps up, instead of adding new items behind the sticky header.

**Comment by ealymbaev** [comment]
@jacobtabak Could you please review this issue?

**Comment by jacobtabak** [comment]
Yep, traveling this week though, I'll try to find time soon.

**Comment by jacobtabak** [comment]
@ealymbaev sorry for the delay - is this still an issue for you?

**Comment by ealymbaev** [comment]
@jacobtabak Yes, the issue is still the same. It would be great if you could resolve it asap.

**Comment by jacobtabak** [comment]
@ealymbaev It seems to work as expected for me with the following additions. Note that item animators aren't really supported in this lib (#5)

```
recyclerView.setItemAnimator(null);
layoutManager.setStackFromEnd(true);
```

**Comment by ealymbaev** [comment]
@jacobtabak Thank you very much. This really solves the issue.Indeed I had set all item animation durations to 0, instead of removing the item animator itself. My bad.

**Comment by jacobtabak** [comment]
No problem, really sorry it took so long for me to look at it! It makes it
really easy when you fork the sample and reproduce the issue.
