### ISSUE TITLE
Get Position of HeaderView

### ISSUE THREAD

**Issue by shivanic1986** [timehop/sticky-headers-recyclerview#94]
Hello Everyone,

I want to open popup menu for Header Item.
I am able to get HeaderView Touch event but not it's actual position on screen.
I debug the code but findHeaderPositionUnder(int x, int y) has not updated Rect()
of HeaderView.
Is it possible to get?

**Comment by jacobtabak** [comment]
Look at the code for the header click listener. You should be able to
modify it to do what you want.

**Comment by shivanic1986** [comment]
@jacobtabak Thank you sir for right direction. I changed StickyRecyclerHeadersDecoration#findHeaderPositionUnder and saved Rect of selected item.

**Comment by shivanic1986** [comment]
Hello sir,

This is my code.
It is giving me incorrect Rect.

https://gist.github.com/shivanic1986/16299fe241d2690e963b#file-stickyrecyclerheadersdecoration-java

Thanks

**Comment by shivanic1986** [comment]
I solved using scroll Position of RecyclerView.

Thanks,
Shivani.

**Comment by BhuvneshK9** [comment]
Hello sir, 
      I am also facing this issue please help me. In case of header view click it return position 0 we need position of its associated view. Please help me how can I solve using scroll position.

Thanks,
Bhuvnesh

**Comment by shivanic1986** [comment]
Hello @BhuvneshK9 

You have to create your own Touch listener for it.

`int position = mDecor.findHeaderPositionUnder((int) e.getX(), (int) e.getY());
if (position != -1) {
View headerView = mDecor.getHeaderView(mRecyclerView, position);
long headerId = getAdapter().getHeaderId(position);
mOnHeaderClickListener.onHeaderClick(headerView, position, headerId);
mRecyclerView.playSoundEffect(SoundEffectConstants.CLICK);
headerView.onTouchEvent(e);
processTouchEvent(headerView, e);
return true;
}
return false;`

where mDecor is StickyRecyclerHeadersDecoration.

Hope this helps.

Thanks,
Shivani

**Comment by BhuvneshK9** [comment]
Hello @shivanic1986 ,

In above code. what is processTouchEvent(headerView, e); 

Here is my  StickyRecyclerHeadersTouchListener.java class,
https://gist.github.com/BhuvneshK9/ae2817a46563b06e9c4d

That is not working for me.

Thanks for your kind consideration ,
Bhuvnesh

**Comment by Nizomjon1994** [comment]
Please help us. It is really important can u give us full code
